[package]
authors = ["David A. Wheeler <dwheeler@dwheeler.com>", "Stefan O'Rear <sorear2@gmail.com>"]
license = "MIT OR Apache-2.0"
name = "metamath-knife"
readme = "README.md"
version = "3.1.0-1"
description = "A parallel and incremental verifier for Metamath databases"
repository = "https://github.com/david-a-wheeler/metamath-knife"
edition = "2018"

[dependencies]
clap = "2.5.2"
filetime = "0.1.10"
fnv = "1.0.7"
regex = "0.1.71"

[features]
sysalloc = []

[profile]

[profile.release]
codegen-units = 1
debug = true

[profile.dev]
opt-level = 1
codegen-units = 4

[profile.test]
codegen-units = 4
