[package]
authors = ["Stefan O'Rear <stefanor@cox.net>"]
name = "smetamath"
version = "3.0.0-1"

[dependencies]
clap = "2.5.2"
fnv = "1.0.2"

[profile]

[profile.release]
codegen-units = 1
debug = true
